server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8 # 요청/응답의 문자셋을 UTF-8 으로 지정
      enabled: true # 인코딩 필터 활성화
      force: true #클라이언트가 다른 인코딩으로 지정해도 UTF-8 강제 적용
logging:
  level:
    root: INFO
    com.example: INFO
    jung: INFO
    io.grpc: INFO
    net.devh.boot.grpc: INFO
    org.springframework.security: DEBUG

jwt:
  secret_key: Q5k8eK7r9P4vZ1xY0aN+7mHc2uZ0D1S4n8wJ6rE9A=45461616161
  expired: 360000
  refresh-expired: 1209600000
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/study
    username: root
    password: abc123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: abc123!
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: '6OK3B082=OUt9j2lC8OW'
  jpa:
    hibernate:
      ddl-auto: update   # 개발용
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: webhook-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
grpc:
  server:
    port: 9090
  client:
    user-service:
      address: static://localhost:9090
      negotiation-type: plaintext
solana:
  rpc:
    url: https://api.devnet.solana.com
  usdc-mint: 4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU #devNet
wallet:
  mnemonic: upgrade explain play elbow earn spatial march loan bid suit nest fresh
webhook:
  secret: 3f2a1b9c8d7e6f5a4b3c2d1e0f9a8b7c
  site : https://webhook.site/1b33c2ea-4434-42a3-b6d6-280bb9c4712f

cors:
  allowed-origins:
  - "http://localhost:3000"
  - "http://localhost:3001"
  - "http://localhost:3002"
